### ISSUE TITLE
Support more irregular spaces

### ISSUE THREAD

**Issue by MohamedLamineAllal** [karlito40/fix-irregular-whitespace#3]
Reading the code source i noticed only one irregular space is handled! And i imagine it's (ALT + SPACE) irregular whitespace!

You can find what are interesting irregular whitespace to treat here within the eslint rule for it:

https://eslint.org/docs/rules/no-irregular-whitespace

It happen that i wrote an article about irregular spaces and fixing them! And i featured this extension!

https://allalmohamedlamine.medium.com/fixing-and-removing-irregular-spaces-984389e17132

I can send a PR too! If you want me to!

Ty for the great extension!

**Comment by karlito40** [comment]
Wow thanks for the feedback. 

You are right. The extension only replace "alt+space" whitespace.

I would also replace the others but unfortunately i'm not able to generate them. The "ALT+code" tips does not work on my keyboard. So i was not confident to blindly replace those ones.

You can make a PR if you want. I'll push a new version with your code. 

If you don't, i'll try to add those whitespace around March 30 as i will be a bit busy this week.

**Comment by MohamedLamineAllal** [comment]
I'll fill a PR soon (During this week)! And make a test for it!

**Comment by MohamedLamineAllal** [comment]
https://github.com/karlito40/fix-irregular-whitespace/pull/4
