### ISSUE TITLE
No active editor found when applying "Fix irregular whitespace in workspace" 

### ISSUE THREAD

**Issue by tiavina-mika** [karlito40/fix-irregular-whitespace#6]
Command pallet (CTRL + SHIFT + P) and:
> Fix irregular whitespace in workspace

In my root project I have 2 folders:
`/client` and `/server`
I want to fix the /client folder but have this error in vscode:
`No active editor found`

![image](https://user-images.githubusercontent.com/42656064/165457197-4b53f6bb-bab8-4fff-bba6-1fe3c48fc210.png)

**Comment by tiavina-mika** [comment]
Solved!
It should be in the project root to run `Fix irregular whitespace in workspace`

**Comment by karlito40** [comment]
Sorry i missed the notification. But glad you found the solution 👍
