### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ksathyanm** [karlito40/fix-irregular-whitespace#8]
@karlito40 @MohamedLamineAllal Can you please add License to the repo?

**Comment by karlito40** [comment]
Hello ! Thanks for the comment 👍

I added the WTFP license. Don't mind the "brutal" text. It's a fully legal and legit license as explain on wikipedia [wikipedia.org/wiki/WTFPL](wikipedia.org/wiki/WTFPL)
